# Generated by Django 5.1.6 on 2025-03-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='Wikipedia article URL')),
                ('snippet', models.TextField(blank=True, help_text='Short summary or snippet from the article')),
                ('rating', models.PositiveIntegerField(default=3, help_text='Rate this article from 1 (lowest) to 5 (highest).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('channel', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(help_text='Link to the YouTube video')),
                ('description', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(default=3, help_text='Rate this video from 1 (lowest) to 5 (highest).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='youtuberesource',
            name='user',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, help_text='Link to purchase or info (e.g., Amazon, publisher)'),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.PositiveIntegerField(default=3, help_text='Rate this book from 1 (lowest) to 5 (highest).'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='WikipediaArticle',
        ),
        migrations.DeleteModel(
            name='YoutubeResource',
        ),
    ]
