# Generated by Django 5.1.6 on 2025-03-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_wikiresource_youtubevideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, help_text='Link to purchase or info'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveIntegerField(default=3, help_text='1 to 5'),
        ),
        migrations.AlterField(
            model_name='wikiresource',
            name='rating',
            field=models.PositiveIntegerField(default=3, help_text='1 to 5'),
        ),
        migrations.AlterField(
            model_name='wikiresource',
            name='snippet',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='link',
            field=models.URLField(help_text='YouTube video link'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='rating',
            field=models.PositiveIntegerField(default=3, help_text='1 to 5'),
        ),
    ]
