# Generated by Django 5.1.6 on 2025-03-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Personal', 'Personal'), ('Work', 'Work'), ('Study', 'Study')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g. "django, python, tutorial")', max_length=200),
        ),
    ]
