# Generated by Django 5.1.6 on 2025-03-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='user',
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(),
        ),
    ]
